import { BlockType } from './types';

export interface ExerciseTemplate {
  name: string;
  defaultSets?: string;
  defaultReps?: string;
  defaultDuration?: string;
  defaultIntensity?: string;
}

export const exerciseDatabase: Record<BlockType, ExerciseTemplate[]> = {
  Cardio: [
    { name: 'Carrera Continua', defaultDuration: '30 min', defaultIntensity: 'Zona 2' },
    { name: 'Intervalos 400m', defaultSets: '5', defaultDuration: '90 seg', defaultIntensity: 'Zona 4-5' },
    { name: 'Intervalos 1km', defaultSets: '4', defaultDuration: '4-5 min', defaultIntensity: 'Zona 4-5' },
    { name: 'Fartlek', defaultDuration: '30 min', defaultIntensity: 'Zona 2-4' },
    { name: 'Tempo Run', defaultDuration: '20 min', defaultIntensity: 'Zona 3-4' },
    { name: 'Ciclismo Base', defaultDuration: '60 min', defaultIntensity: 'Zona 2' },
    { name: 'Natación Libre', defaultDuration: '30 min', defaultIntensity: 'Moderada' },
    { name: 'Natación Técnica', defaultDuration: '45 min', defaultIntensity: 'Zona 2' },
    { name: 'Remo Ergómetro', defaultDuration: '20 min', defaultIntensity: 'Zona 3' },
    { name: 'Elíptica', defaultDuration: '45 min', defaultIntensity: 'Zona 2' },
    { name: 'Saltar la Cuerda', defaultDuration: '15 min', defaultIntensity: 'Alta' },
    { name: 'HIIT 20 min', defaultDuration: '20 min', defaultIntensity: 'Zona 4-5' },
    { name: 'Sprint 100m', defaultSets: '10', defaultDuration: '15 seg', defaultIntensity: 'Máxima' },
    { name: 'Bicicleta de Montaña', defaultDuration: '90 min', defaultIntensity: 'Zona 2-3' },
    { name: 'Caminata Rápida', defaultDuration: '45 min', defaultIntensity: 'Zona 1-2' },
    { name: 'Triatlón - Natación', defaultDuration: '45 min', defaultIntensity: 'Zona 2-3' },
    { name: 'Triatlón - Ciclismo', defaultDuration: '60 min', defaultIntensity: 'Zona 2-3' },
    { name: 'Cross Training', defaultDuration: '40 min', defaultIntensity: 'Moderada' },
    { name: 'Carrera de Montaña', defaultDuration: '75 min', defaultIntensity: 'Zona 2-3' },
    { name: 'Stairclimber', defaultDuration: '30 min', defaultIntensity: 'Zona 3' },
    { name: 'Kickboxing Cardio', defaultDuration: '30 min', defaultIntensity: 'Alta' },
    { name: 'Carrera Progresiva', defaultDuration: '40 min', defaultIntensity: 'Zona 2→4' },
  ],
  Halterofilia: [
    { name: 'Sentadilla Trasera', defaultSets: '4', defaultReps: '8', defaultIntensity: 'RPE 7' },
    { name: 'Sentadilla Frontal', defaultSets: '4', defaultReps: '6', defaultIntensity: 'RPE 8' },
    { name: 'Press de Banca', defaultSets: '4', defaultReps: '6', defaultIntensity: 'RPE 8' },
    { name: 'Press de Banca Inclinado', defaultSets: '3', defaultReps: '10', defaultIntensity: 'RPE 7' },
    { name: 'Peso Muerto', defaultSets: '3', defaultReps: '5', defaultIntensity: 'RPE 8' },
    { name: 'Peso Muerto Rumano', defaultSets: '3', defaultReps: '10', defaultIntensity: 'RPE 7' },
    { name: 'Prensa de Pierna', defaultSets: '3', defaultReps: '12', defaultIntensity: 'RPE 7' },
    { name: 'Remo con Barra', defaultSets: '4', defaultReps: '8', defaultIntensity: 'RPE 7' },
    { name: 'Remo Unilateral', defaultSets: '3', defaultReps: '10', defaultIntensity: 'RPE 7' },
    { name: 'Press Militar', defaultSets: '3', defaultReps: '10', defaultIntensity: 'RPE 7' },
    { name: 'Curl de Bíceps', defaultSets: '3', defaultReps: '12', defaultIntensity: 'RPE 6' },
    { name: 'Extensión de Tríceps', defaultSets: '3', defaultReps: '12', defaultIntensity: 'RPE 6' },
    { name: 'Jalón al Pecho', defaultSets: '4', defaultReps: '10', defaultIntensity: 'RPE 7' },
    { name: 'Zancadas', defaultSets: '3', defaultReps: '10', defaultIntensity: 'RPE 7' },
    { name: 'Hip Thrust', defaultSets: '4', defaultReps: '12', defaultIntensity: 'RPE 7' },
    { name: 'Pull-up', defaultSets: '3', defaultReps: '8', defaultIntensity: 'RPE 8' },
    { name: 'Dips', defaultSets: '3', defaultReps: '10', defaultIntensity: 'RPE 7' },
    { name: 'Plancha', defaultSets: '3', defaultDuration: '60 seg', defaultIntensity: 'RPE 6' },
    { name: 'Crunch Abdominal', defaultSets: '3', defaultReps: '20', defaultIntensity: 'RPE 5' },
    { name: 'Russian Twist', defaultSets: '3', defaultReps: '20', defaultIntensity: 'RPE 6' },
    { name: 'Elevación de Piernas', defaultSets: '3', defaultReps: '15', defaultIntensity: 'RPE 6' },
    { name: 'Elevaciones Laterales', defaultSets: '3', defaultReps: '15', defaultIntensity: 'RPE 6' },
    { name: 'Face Pull', defaultSets: '3', defaultReps: '15', defaultIntensity: 'RPE 6' },
    { name: 'Good Morning', defaultSets: '3', defaultReps: '10', defaultIntensity: 'RPE 6' },
  ],
  Flexibilidad: [
    { name: 'Estiramiento Isquiotibiales', defaultDuration: '60 seg', defaultIntensity: 'Suave' },
    { name: 'Yoga Vinyasa', defaultDuration: '30 min', defaultIntensity: 'Moderada' },
    { name: 'Stretching Dinámico', defaultDuration: '15 min', defaultIntensity: 'Suave' },
    { name: 'Movilidad de Cadera', defaultDuration: '20 min', defaultIntensity: 'Suave' },
    { name: 'Estiramiento de Hombros', defaultDuration: '30 seg', defaultIntensity: 'Suave' },
    { name: 'Yoga Restaurativo', defaultDuration: '45 min', defaultIntensity: 'Suave' },
    { name: 'Foam Roller General', defaultDuration: '20 min', defaultIntensity: 'Suave' },
    { name: 'Estiramiento de Cuádriceps', defaultDuration: '60 seg', defaultIntensity: 'Suave' },
    { name: 'Movilidad de Tobillo', defaultDuration: '10 min', defaultIntensity: 'Suave' },
    { name: 'Pilates', defaultDuration: '30 min', defaultIntensity: 'Moderada' },
    { name: 'Estiramiento de Pantorrillas', defaultDuration: '60 seg', defaultIntensity: 'Suave' },
    { name: 'Apertura de Cadera (90/90)', defaultDuration: '2 min', defaultIntensity: 'Suave' },
    { name: 'Rotación Torácica', defaultSets: '2', defaultReps: '10', defaultIntensity: 'Suave' },
    { name: 'Flexión de Columna', defaultDuration: '30 seg', defaultIntensity: 'Suave' },
    { name: 'Movilidad de Hombro', defaultDuration: '5 min', defaultIntensity: 'Suave' },
    { name: 'Pigeon Pose', defaultDuration: '90 seg', defaultIntensity: 'Suave' },
    { name: 'Cat-Cow', defaultSets: '2', defaultReps: '10', defaultIntensity: 'Suave' },
  ],
  'Deporte Específico': [
    { name: 'Pliometría - Saltos en Cajón', defaultSets: '4', defaultReps: '10', defaultDuration: '10 min', defaultIntensity: 'Alta' },
    { name: 'Escalera de Agilidad', defaultSets: '3', defaultDuration: '3 min', defaultIntensity: 'Alta' },
    { name: 'Cambio de Dirección', defaultSets: '3', defaultReps: '5', defaultDuration: '15 min', defaultIntensity: 'Alta' },
    { name: 'Salto Horizontal', defaultSets: '4', defaultReps: '5', defaultIntensity: 'Alta' },
    { name: 'Salto Vertical', defaultSets: '3', defaultReps: '8', defaultIntensity: 'Alta' },
    { name: 'Medicine Ball Slam', defaultSets: '3', defaultReps: '10', defaultIntensity: 'Alta' },
    { name: 'Kettlebell Swing', defaultSets: '4', defaultReps: '15', defaultIntensity: 'Moderada' },
    { name: 'Battle Ropes', defaultSets: '4', defaultDuration: '30 seg', defaultIntensity: 'Alta' },
    { name: 'Box Jump', defaultSets: '3', defaultReps: '8', defaultIntensity: 'Alta' },
    { name: 'Lateral Shuffle', defaultSets: '3', defaultDuration: '30 seg', defaultIntensity: 'Alta' },
    { name: 'Sprint Resistido', defaultSets: '6', defaultDuration: '30m', defaultIntensity: 'Máxima' },
    { name: 'Arrastre de Trineo', defaultSets: '4', defaultDuration: '20m', defaultIntensity: 'Alta' },
    { name: 'Lanzamiento de Balón', defaultSets: '3', defaultReps: '10', defaultIntensity: 'Alta' },
    { name: 'Carrera con Paracaídas', defaultSets: '5', defaultDuration: '50m', defaultIntensity: 'Máxima' },
    { name: 'T-Test Agilidad', defaultSets: '4', defaultDuration: '10-12 seg', defaultIntensity: 'Alta' },
    { name: 'Salto Profundo', defaultSets: '3', defaultReps: '6', defaultIntensity: 'Alta' },
  ],
  Recuperación: [
    { name: 'Caminata Suave', defaultDuration: '30 min', defaultIntensity: 'Muy Baja' },
    { name: 'Natación Relajada', defaultDuration: '20 min', defaultIntensity: 'Zona 1' },
    { name: 'Yoga Restaurativo', defaultDuration: '30 min', defaultIntensity: 'Muy Baja' },
    { name: 'Foam Rolling Completo', defaultDuration: '15 min', defaultIntensity: 'Suave' },
    { name: 'Baño de Hielo', defaultDuration: '10-15 min', defaultIntensity: 'Pasivo' },
    { name: 'Masaje de Recuperación', defaultDuration: '30 min', defaultIntensity: 'Pasivo' },
    { name: 'Stretching Pasivo', defaultDuration: '20 min', defaultIntensity: 'Muy Baja' },
    { name: 'Respiración Profunda', defaultDuration: '10 min', defaultIntensity: 'Pasivo' },
    { name: 'Ciclismo de Recuperación', defaultDuration: '30 min', defaultIntensity: 'Zona 1' },
    { name: 'Contraste Calor/Frío', defaultDuration: '20 min', defaultIntensity: 'Pasivo' },
    { name: 'Compresión Neumática', defaultDuration: '20 min', defaultIntensity: 'Pasivo' },
    { name: 'Meditación', defaultDuration: '15 min', defaultIntensity: 'Pasivo' },
  ],
  Otro: [
    { name: 'Calentamiento General', defaultSets: '1', defaultDuration: '10 min', defaultIntensity: 'Baja' },
    { name: 'Vuelta a la Calma', defaultDuration: '10 min', defaultIntensity: 'Muy Baja' },
    { name: 'Test de Evaluación', defaultSets: '1', defaultReps: '1', defaultDuration: '30 min', defaultIntensity: 'Variable' },
    { name: 'Activación Neuromuscular', defaultSets: '2', defaultReps: '10', defaultDuration: '5 min', defaultIntensity: 'Moderada' },
    { name: 'Potencia - Arrancada', defaultSets: '5', defaultReps: '3', defaultIntensity: 'RPE 8' },
    { name: 'Potencia - Cargada', defaultSets: '5', defaultReps: '3', defaultIntensity: 'RPE 8' },
    { name: 'Entrenamiento Mental', defaultDuration: '15 min', defaultIntensity: 'Pasivo' },
    { name: 'Técnica de Respiración', defaultSets: '3', defaultDuration: '5 min', defaultIntensity: 'Baja' },
    { name: 'Coordinación y Equilibrio', defaultSets: '3', defaultReps: '10', defaultDuration: '10 min', defaultIntensity: 'Moderada' },
    { name: 'Ejercicio Personalizado', defaultSets: '', defaultReps: '', defaultDuration: '', defaultIntensity: '' },
  ],
};
